- src/ExplicitImports.jl
- src/checks.jl
- test/runtests.jl
I want to get this in before v1.0 is tagged, so we can add richer outputs without breaking things. Xref https://github.com/ericphanson/ExplicitImports.jl/issues/4.
> refactor to use `NamedTuple` outputs

- README.md
- src/ExplicitImports.jl
- src/checks.jl
- test/runtests.jl
closes #4 
Can be handy for debugging and MWEs
> Add `show_locations` kwarg to print the location of the name being used from global namespace

- Project.toml
- src/get_names_used.jl
- test/Exporter.jl
- test/TestModA.jl
- test/runtests.jl
closes #15 
On this branch I get:
````julia
julia> using ExplicitImports, Lux
julia> print_explicit_imports(Lux)
Module Lux is relying on implicit imports for 54 names. These could be explicitly imported as follows:
```julia
using Adapt: Adapt
using Adapt: adapt
using ArrayInterface: ArrayInterface
using ChainRulesCore: ChainRulesCore
using ChainRulesCore: AbstractZero
using ChainRulesCore: HasReverseMode
using ChainRulesCore: NoTangent
using ChainRulesCore: ProjectTo
using ChainRulesCore: RuleConfig
using ChainRulesCore: ZeroTangent
using ConcreteStructs: ConcreteStructs
using ConcreteStructs: @concrete
using Functors: Functors
using Functors: fmap
using GPUArraysCore: GPUArraysCore
using LinearAlgebra: LinearAlgebra
using LuxCore: LuxCore
using LuxDeviceUtils: LuxDeviceUtils
using …
> handle macronames

- Project.toml
- src/get_names_used.jl
- test/examples.jl
- test/runtests.jl
closes https://github.com/ericphanson/ExplicitImports.jl/issues/20
Note: I expect we are still not correctly identifying function arguments correctly as local variables in macro or string macro definitions, i.e. #8 for macros / string macros. But at least that should be much rarer, so seems less urgent.
> detect string macro usages

- Project.toml
- docs/src/api.md
- src/ExplicitImports.jl
- test/runtests.jl
- test/script.jl
closes https://github.com/ericphanson/ExplicitImports.jl/issues/19
````julia
julia> print_explicit_imports_script("script.jl")
Script `script.jl` is relying on implicit imports for 1 names. These could be explicitly imported as follows:
```julia
using LinearAlgebra: norm
```
Additionally, script `script.jl` has stale explicit imports for these unused names:
- qr
````
I think this should also include `using LinearAlgebra: LinearAlgebra`, but that doesn't work, since `which(Main, :LinearAlgebra) === Main` (whereas I think it should be `LinearAlgebra). I filed https://github.com/JuliaLang/julia/issues/53576 for that.
> add script functionality

- Project.toml
- src/ExplicitImports.jl
- src/checks.jl
- src/find_implicit_imports.jl
- test/examples.jl
- test/runtests.jl
closes #24
On this branch I get:
````julia
julia> print_explicit_imports(MixedModels)
WARNING: both Distributions and BSplineKit export "support"; uses of it in module MixedModels must be qualified
Module MixedModels is relying on implicit imports for 162 names. These could be explicitly imported as follows:
```julia
using Arrow: Arrow
using BSplineKit: BSplineKit
using BSplineKit: BSplineOrder
using BSplineKit: Natural
using BSplineKit: Derivative
using BSplineKit: SplineInterpolation
using BSplineKit: interpolate
using DataAPI: DataAPI
using Distributions: Distributions
using GLM: Bernoulli
using GLM: Binomial
using Distributions: Chisq
using Distributions: Distribution
using GLM: Gamma
using GLM: InverseGaussian
using GLM: Normal
using GLM: Poisson
using Distributions: ccdf
using …
> Print a module that exports the name rather than the module that defines the name

- Project.toml
- README.md
- src/ExplicitImports.jl
- test/runtests.jl
I prefer this format a bit more:
````julia
julia> print_explicit_imports(MixedModels)
Module MixedModels is relying on implicit imports for 162 names. These could be explicitly imported as follows:
```julia
using Arrow: Arrow
using BSplineKit: BSplineKit, BSplineOrder, Derivative, Natural,
SplineInterpolation, interpolate
using DataAPI: DataAPI
using Distributions: Distributions, Chisq, Distribution, ccdf, estimate
using GLM: GLM, Bernoulli, Binomial, Gamma, GeneralizedLinearModel,
IdentityLink, InverseGaussian, InverseLink, LinearModel, LogLink,
LogitLink, Normal, Poisson, ProbitLink, SqrtLink, glm
using JSON3: JSON3
using LinearAlgebra: LinearAlgebra, Adjoint, BLAS, ColumnNorm, Diagonal,
Hermitian, I, LAPACK, LowerTriangular, SVD,
SymTridiagonal, Symmetric, UpperTriangular, cond, diag, …
> format `using` statements

- Project.toml
- src/parse_utilities.jl
- test/DynMod.jl
- test/runtests.jl
closes https://github.com/ericphanson/ExplicitImports.jl/issues/30
Turns out this happens when there's an `include` with interpolation (remembered https://github.com/JuliaEcosystem/PackageAnalyzer.jl/pull/79#discussion_r1199692128)
> fix bug when `include` statement includes interpolation

- src/get_names_used.jl
- test/runtests.jl
- test/test_mods.jl
I saw https://github.com/JuliaLang/JuliaSyntax.jl/issues/432 posted in slack, which alerted me to the fact I wasn't handling cartesian iteration correctly. If that issue is closed we'll need an update here as well.
> handle cartesian iteration inside for syntax

- Project.toml
- src/ExplicitImports.jl
- test/examples.jl
- test/runtests.jl
closes https://github.com/ericphanson/ExplicitImports.jl/issues/29
I realized after looking into this one that we almost handle it correctly already, there is just an incorrect `skip`
> don't skip source modules

- .github/workflows/CI.yml
- Project.toml
- README.md
- docs/src/api.md
- docs/src/internals.md
- examples/qualified.jl
- src/ExplicitImports.jl
- src/checks.jl
- src/get_names_used.jl
- src/qualified_names.jl
- test/TestModC.jl
- test/public_compat.jl
- test/runtests.jl
- test/test_qualified_access.jl
closes #48 
I think I've got the rough functionality working:
```julia
julia> ExplicitImports.improper_qualified_names_nonrecursive(ExplicitImports)
1 issues with qualified names were found:
- `parent` has parentmodule AbstractTrees but it was accessed from ExplicitImports at /Users/eph/ExplicitImports/src/qualified_names.jl:78:21
```
It isn't clear to me whether or not what matters is `parentmodule`, `which`, or maybe in 1.11, `ispublic`... I might mark this experimental and choose to change the criteria later.
before merging, needs:
and possibly in a followup:
> Provide functionality to detect "improper qualified access"

- src/checks.jl
- src/deprecated.jl
- src/improper_explicit_imports.jl
- src/improper_qualified_accesses.jl
- src/interactive_usage.jl
- test/deprecated.jl
- test/runtests.jl
- test/test_qualified_access.jl
I expect this would be more annoying than not in most cases
> By default, ignore "improper" imports/accesses from within the same package

- src/ExplicitImports.jl
- src/checks.jl
- src/improper_explicit_imports.jl
- src/improper_qualified_accesses.jl
- test/runtests.jl
- test/test_mods.jl
closes https://github.com/ericphanson/ExplicitImports.jl/issues/70
> use `skip` mechanism to skip imports/access of names from Compat that are owned by Base

- src/ExplicitImports.jl
This avoids a warning when loading the package while creating an ~used~ ununsed explicit import.  The former occurs for all users, the latter only for developers of this package.
Closes #77.
> explicitly import `parse`

- README.md
The readme contains a reference to an `implicit_imports` method that does not exist. It seems like it should reference `explicit_imports` instead, which is what this PR changes.
> Fix ref to `explicit_imports` in readme

- Project.toml
Since we already have an `@main` this is all that is needed for 1.12's app support. The only question is what to name the CLI app; here I've chosen `explicit-imports`.
> add app `explicit-imports-jl`

- Project.toml
- README.md
- src/ExplicitImports.jl
- src/get_names_used.jl
- src/main.jl
because apps run with a very restricted `LOAD_PATH`, the previous way of loading the package in `main` wasn't working. This seems to fix it.
It is not easy to test because we need to install the app to test that part (we already test the `-m` functionality with another process), but I hope eventually we can. For now it is experimental functionality so I think it's alright.
> fix package loading in app use-case

- src/ExplicitImports.jl
- src/find_implicit_imports.jl
- src/get_names_used.jl
- src/improper_explicit_imports.jl
- src/improper_qualified_accesses.jl
- src/interactive_usage.jl
- src/precompile.jl
some of these changes make JET happier, but I think only the precompiles do anything for the actual TTFX, which improves it by ~0.3s, going from 2.3s to 2s on example.jl.
> try to improve inferability and ttfx

- src/checks.jl
- src/interactive_usage.jl
- src/precompile.jl
- test/Test_Mod_Underscores.jl
- test/runtests.jl
Before output looked like e.g.
```
•  is_eq has owner RAIIR but it was imported from RAIBackIR at src/Quxbaz.jl:44:14
```
whereas now it looks like
```
•  is_eq has owner RAI_IR but it was imported from RAI_BackIR at src/Qux_baz:44:14
```
-- 
Also fix a precompile warning
> Print modules and files wrapped in backticks so that names with `_` don't cause italics

- .github/workflows/CompatHelper.yml
I noticed the CompatHelper actions seem to be failing with a permissions issue. I believe this should fix it (see also the template provided [here](https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml)).
> Add write permissions to CompatHelper action

- .gitignore
- Project.toml
- src/find_implicit_imports.jl
- src/improper_explicit_imports.jl
- test/module_alias.jl
- test/runtests.jl
I'm pretty sure we can just delete this error path, my assumption wasn't right but it doesn't matter. The check was intended for other problems that haven't arose.
closes #106
> bugfix: support module aliases

- .github/workflows/CI.yml
- Project.toml
- docs/src/internals.md
- src/ExplicitImports.jl
- src/checks.jl
- src/deprecated.jl
- src/get_names_used.jl
- src/improper_explicit_imports.jl
- src/improper_qualified_accesses.jl
- test/main.jl
- test/runtests.jl
- test/test_mods.jl
This drops support for julia before 1.10 now that it is the LTS, and moves Compat.jl to a test-only dependency. This is because in #121 I want to use dispatch on module parameters which requires at least 1.10. It also simplifies things by having less branching in the tests for various features.
> Drop support for pre-1.10 Julia

- Project.toml
- src/ExplicitImports.jl
I ran into https://github.com/JuliaTesting/ExplicitImports.jl/issues/93 in a (non-public) package where tests are run with `--depwarn=error`. It seems that the problematic change was introduced in https://github.com/JuliaTesting/ExplicitImports.jl/pull/17 but as this package does not support Julia < 1.10 anymore, I reverted it.
With this PR, downstream tests do not fail anymore (but the deprecation warnings of the deprecated bindings are displayed since it is accessed with `getglobal`).
Fixes #93.
---
To some extent, the issue here is similar to https://github.com/JuliaDocs/Documenter.jl/issues/2758. In principle, one could apply the same approach as done in Base in Julia <= 1.11 and check `Base.isbindingresolved(mod, name)` before trying to access `getglobal(mod, name)` to avoid …
> Fix ExplicitImports to work with `--depwarn=error`
