JuliaTesting/ExplicitImports.jl

Project.toml
src/ExplicitImports.jl
src/checks.jl
src/get_names_used.jl
src/parse_utilities.jl
test/DynMod.jl
test/TestModArgs.jl
test/examples.jl
test/runtests.jl

Fixes #1  re-fixes https://github.com/ericphanson/ExplicitImports.jl/issues/2
WIP, still need to handle type parameters...
Based off of #7 which I'll merge first.

Properly detect function args as local variables

---

README.md
docs/src/index.md

Update docs badge

---

.github/workflows/CI.yml
Project.toml
src/ExplicitImports.jl

xref https://discourse.julialang.org/t/ann-explicitimports-jl-tooling-to-help-use-and-maintain-explicit-imports-in-your-package/110973/7

Support Julia 1.7

---

.gitignore
Project.toml
src/ExplicitImports.jl
test/TestPkg/Project.toml
test/TestPkg/ext/DataFramesExt.jl
test/TestPkg/ext/included_file.jl
test/TestPkg/src/TestPkg.jl
test/runtests.jl

Fixes #14 
I am not too sure how to simulate the loading of a package extension for testing

Detect Extensions if loaded

---

src/get_names_used.jl
test/TestModArgs.jl
test/runtests.jl

I noted this was missing in #21

detect local args in macro definitions

---

src/get_names_used.jl
test/runtests.jl
test/test_mods.jl

Fix some false positives in struct definitions

---

src/get_names_used.jl
src/parse_utilities.jl
test/runtests.jl
test/test_mods.jl

handle for loop arguments and nested local scope

---

Project.toml
src/get_names_used.jl
test/runtests.jl

The fix for #35 was messy, and this code in general is pretty gnarly. Here I have tried to streamline the logic and the processing, and ensure there is rich intermediate output for better debugging. Some bugs were being covered by redundant code paths, so streamlining surfaced them. I'm not sure if there are observable changes in the end, but I will tag anyway since there may be improvements in edge cases.

Refactor and cleanup some of the code

---

src/get_names_used.jl
test/runtests.jl
test/test_mods.jl

These weren't handled at all previously

Handle generators

---

src/get_names_used.jl
test/runtests.jl
test/test_mods.jl

this is tricky! need to keep a bit more state, since `do` does not introduce scope to all it's children, only the 2nd two

handle do-syntax

---

src/get_names_used.jl
test/TestModC.jl
test/runtests.jl

track qualifying modules

---

README.md
docs/src/api.md
src/ExplicitImports.jl
src/checks.jl
src/improper_explicit_imports.jl
test/runtests.jl

add `check_all_explicit_imports_are_public`

---

Project.toml
README.md
docs/src/api.md
src/ExplicitImports.jl
src/checks.jl
src/improper_qualified_accesses.jl
src/interactive_usage.jl
test/runtests.jl
test/test_qualified_access.jl

add `check all qualified accesses are public`

---

README.md
test/runtests.jl
test/test_mods.jl

I tried to fix it but it seems too hard right now. The easiest thing is to just wait for JuliaLowering I think.

document bug from #62

---

README.md
docs/src/api.md
src/ExplicitImports.jl
src/checks.jl
src/improper_qualified_accesses.jl
src/interactive_usage.jl
test/runtests.jl
test/test_mods.jl
test/test_qualified_access.jl

closes https://github.com/ericphanson/ExplicitImports.jl/issues/55

add `check_no_self_qualified_accesses`

---

Project.toml
src/ExplicitImports.jl
src/interactive_usage.jl
test/runtests.jl

xref https://discourse.julialang.org/t/ann-explicitimports-jl-tooling-to-help-use-and-maintain-explicit-imports-in-your-package/110973/16

allow printing on separate lines in `print_explicit_imports`

---

.github/workflows/CI.yml
Project.toml
src/ExplicitImports.jl
src/checks.jl
src/deprecated.jl
src/get_names_used.jl
src/improper_explicit_imports.jl
src/improper_qualified_accesses.jl
src/interactive_usage.jl
test/runtests.jl
test/test_mods.jl

it adds a dependency and makes the code uglier, but probably it's good to support the LTS
towards https://github.com/ericphanson/ExplicitImports.jl/issues/65

Support Julia 1.6

---

Project.toml
src/improper_explicit_imports.jl
test/runtests.jl
test/test_mods.jl

closes https://github.com/ericphanson/ExplicitImports.jl/issues/69

support code-generated exports in staleness check

---

test/runtests.jl

fix tests: allow DataAPI as source for groupby

---

Project.toml
src/main.jl

Hello again, we missed this change in the last PR. I also took the liberty of updating the version.

Fix checks -> CHECKS in src/main.jl

---

Project.toml
src/find_implicit_imports.jl
test/examples.jl
test/public_compat.jl
test/runtests.jl

Not 100% sure the root cause here so there could still be a lurking issue
closes #88

Fix tests and latent bug around public symbols vs base exports

---

.gitattributes

after #124, the diff still shows non-minimized in #121 so want to mark as generated too
xref https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github

mark linguist-generated
